spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: postgres
    password: 1234
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: off
  application:
    name: order-service
server:
  port: 8081

# Eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka