eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # To prevent registering the server itself as a client
    fetch-registry: false # The server maintains its registry locally
server:
  port: 8761