spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: 1234
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: off
  application:
    name: product-service
server:
  port: 0

# Eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"