spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/product-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
